services:
  db:
    image: mysql:8.0.30
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./db_jpprod.sql:/docker-entrypoint-initdb.d/db_jpprod.sql
    networks:
      - jpnetwork

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: pma
    links:
      - db
    restart: always
    ports:
      - 8081:80
    networks:
      - jpnetwork

  web:
    image: matap
    container_name: web
    volumes:
      - ./p_prod-jp:/var/www/html
    ports:
      - 8080:80
    restart: always
    links:
      - db
    networks:
      - jpnetwork

volumes:
  dbdata:

networks:
  jpnetwork:
    driver: bridge
